local pause = require "scripts.pause" 

local function change_color(node)

	gui.set_color(node, vmath.vector4(128/255, 0, 128/255, 1)) -- changes color to purple
	timer.delay(0.3, false, function()
		gui.set_color(node, vmath.vector4(1, 1, 1, 1)) -- to white
	end)
end


function init(self)
	-- hides the node on initialization
	gui.set_enabled(gui.get_node("root"), false)
end

function on_message(self, message_id, message, sender)
	-- reads the messages and either hides o shows the node
	if message_id == hash("show_pause") then
		-- Show the pause screen
		gui.set_enabled(gui.get_node("root"), true)
		msg.post('.', 'acquire_input_focus')
	elseif message_id == hash("hide_pause") then
		-- Hide the pause screen
		gui.set_enabled(gui.get_node("root"), false)
		msg.post('.', 'release_input_focus') 
	end
end

function on_input(self, action_id, action)
	
	-- handles the soundtrack
	if action_id == hash('touch') and gui.pick_node(gui.get_node('sound_button'), action.x, action.y) then
		msg.post("main:/soundtrack", "sound dial")
		change_color(gui.get_node('sound_button'))
	-- handles the menu button press
	elseif action_id == hash('touch') and gui.pick_node(gui.get_node('menu'), action.x, action.y) then
		-- so that when the game is restarted the update functions are running correctly
		pause.set_pause(not pause.is_paused)
		msg.post('.', 'release_input_focus') 
		print('h')
		msg.post("main:/controller", "play menu")
		change_color(gui.get_node('menu'))
		
	-- handles the continue button
	elseif action_id == hash('touch')and gui.pick_node(gui.get_node('continue'), action.x, action.y) then
		change_color(gui.get_node('continue'))
		--enables the update functions
		pause.set_pause(not pause.is_paused)
		-- Hide the pause screen
		gui.set_enabled(gui.get_node("root"), false)
		msg.post('.', 'release_input_focus') 
	end 
end
