-- used for the pause function
local pause = require "scripts.pause" 

local MOB_SPEED = 20   -- Speed of the mob
local TILE_SIZE = 16   -- Size of a tile

local START_POSITION = vmath.vector3()   -- Starting position of the mob


local function calculate_patrol_distance_bee(self)
	-- these will be the bounds of the patrol 

	self.up_bound = START_POSITION.y
	self.down_bound = START_POSITION.y


	-- starting tile coordinates
	local tile_x = math.floor(START_POSITION.x/TILE_SIZE) + 1
	local tile_y = math.floor(START_POSITION.y/TILE_SIZE) + 1 -- no +1 so its one tile below

	local length_of_patrol = math.random(1,4)
	local direction_of_calculation = -1

	while length_of_patrol > 0 do
		if 	direction_of_calculation == -1 then
			-- right movement
			tile_y = tile_y - 1 -- moves one tile down
			local tile = tilemap.get_tile('/level1#level1_TM', 'ground', tile_x, tile_y) 

			if tile == 0 then -- checks for presence of ground
				self.down_bound = self.down_bound - TILE_SIZE -- increases the bounds
				length_of_patrol = length_of_patrol - 1
			else
				--ground found tiles
				direction_of_calculation = 1 -- switch to up movement
				tile_y = math.floor(START_POSITION.y/TILE_SIZE) + 1 -- reset tile_y
			end
		elseif direction_of_calculation == 1 then
			-- Moving up
			tile_y = tile_y + 1

			local tile = tilemap.get_tile('/level1#level1_TM', 'ground', tile_x, tile_y)

			if tile == 0 then
				-- Expand the upward bound if no ground is found
				self.up_bound = self.up_bound + TILE_SIZE
				length_of_patrol = length_of_patrol - 1
			else
				-- hit ground stop patrol calculation
				break
			end
		end
	end		
end

function on_message(self, message_id, message)
	if message_id == hash("contact_point_response") then
		-- Check if the mob collided with the player
		if message.other_group == hash("character") then
			-- Reverse the bee's velocity to simulate a bounce
			self.velocity.y = -self.velocity.y
			msg.post('/gui#level1_screen', 'Damage',{damage = 5})
		end
		if message.other_group == hash("bullet") then
			-- the bee takes damage
			self.health = self.health - 5
		end
	end
end

function init(self)
	-- Mob position and velocity
	self.position = go.get_position()  -- Starting position
	START_POSITION = vmath.vector3(self.position)
	self.velocity = vmath.vector3(0, MOB_SPEED, 0)
	self.direction = 1  -- 1 means UP, -1 means DOWN
	self.health = 15
	math.randomseed(os.time())
	calculate_patrol_distance_bee(self)
	sprite.set_hflip("#sprite", (math.random(1,2) == 1))

	pause.max_score = pause.max_score + 4 * 3 + 20
end


function update(self, dt)
	
	if pause.is_paused then
		-- Skip updating the game object logic if paused
		return
	end
	
	-- movement 
	self.position.y = self.position.y + self.velocity.y * dt
	-- checks if bee needs to be removed
	if self.health <= 0 then
		-- updates the score for defeating the mob
		msg.post('/gui', 'score update',{score = 20})
		go.delete()
	end
	-- checks bounds and doesnt let the slug go over them
	-- Ensure the mob stays within bounds and reverse direction if needed
	if self.position.y >= self.up_bound then
		self.position.y = self.up_bound
		self.velocity.y = -MOB_SPEED -- Move downward

	elseif self.position.y <= self.down_bound then
		self.position.y = self.down_bound
		self.velocity.y = MOB_SPEED -- Move upward
	end
	go.set_position(self.position)
end
