-- used for the pause function
local pause = require "scripts.pause" 

local MOB_SPEED = 20   -- Speed of the mob
local TILE_SIZE = 16   -- Size of a tile

local START_POSITION = vmath.vector3()   -- Starting position of the mob


local function calculate_patrol_distance(self)
	-- patrol lengths they will be random each instance 
	local length_of_patrol_x = math.random(1,3) * TILE_SIZE
	local length_of_patrol_y = math.random(1,2.5) * TILE_SIZE
	
	-- these will be the bounds of the patrol 
	self.down_left_bound = START_POSITION.y
	self.up_left_bound = START_POSITION.x

	self.down_right_bound = START_POSITION.x +length_of_patrol_x
	self.up_right_bound =  START_POSITION.y + length_of_patrol_y
end

function init(self)
	-- Mob position and velocity
	self.position = go.get_position()  -- Starting position
	START_POSITION = vmath.vector3(self.position)
	self.velocity = vmath.vector3(MOB_SPEED, MOB_SPEED, 0)
	calculate_patrol_distance(self)
	self.direction = 'right'
	self.health = 20
	-- this updates the max score 
	pause.max_score = pause.max_score + 4 * 4 + 25
end

function update(self, dt)
	if pause.is_paused then
		-- Skip updating the game object logic if paused
		return
	end
	
	self.position = go.get_position()
	
	-- cheks if the jet has died and removes from level1_screen
	if self.health <= 0 then
		-- updates the score for defeating the mob
		msg.post('/gui', 'score update',{score = 25})
		go.delete()
	end
	
	-- this is movement it will go round in circles 
	if self.direction == 'right' then
		if self.down_right_bound > self.position.x then
			self.position.x = self.position.x + MOB_SPEED * dt
		else
			self.direction = 'up'
		end
		
	elseif self.direction == 'up' then
		if self.up_right_bound > self.position.y then
			self.position.y = self.position.y + MOB_SPEED * dt
		else
			self.direction = 'left'
		end
		
	elseif self.direction == 'left' then
		if self.up_left_bound < self.position.x then

			self.position.x = self.position.x - MOB_SPEED * dt
		else
			self.direction = 'down'
		end

	elseif self.direction == 'down' then
		if self.down_left_bound < self.position.y then
			self.position.y = self.position.y - MOB_SPEED * dt
		else
			self.direction = 'right'
		end
	end
	sprite.set_hflip("#sprite", (self.direction == 'left' or self.direction == 'up') )

	go.set_position(self.position)
end

function on_message(self, message_id, message)
	--checks for collison with character
	if message_id == hash("contact_point_response") then
		-- handles the damage inflicted by enemy
		if message.other_group == hash("character") then
			msg.post('/gui#level1_screen', 'Damage',{damage = 7})
		end
		-- handles damage inflicted on to enemy
		if message.other_group == hash('bullet') then
			self.health = self.health - 5
		end

	end
end